app:
  name: spring boot application
  config:
    jwt-sign: ${JWT_SIGN:super-secret-sign}
    email-pattern: ${EMAIL_PATTERN:\b[\w\.-]+@[\w\.-]+\.\w{2,4}\b}
    password-pattern: ${PASSWORD_PATTERN:^(?=.*[0-9])(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{4,}}
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  h2:
    console:
      enabled: 'true'
      path: /h2
  datasource:
    username: h2
    url: jdbc:h2:mem:user
    password: h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
